on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '2 * * * *' # every 1 hour for now
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Install requirements
      run: pip install lxml
    - name: Run scraper
      run: python scraper.py
    - name: Commit and push if the data has changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
